### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by fengluoye** [rocket049/powerchat#1]
运行环境：archlinux+i3wm

点击注册之后，软件闪退。

`2019/03/08 20:58:17 www root: /root/ChatShare
2019/03/08 20:58:17 go init.
load name Error: Error opening file /root/.powerchat/manual/loguser.txt: No such file or directory
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x5601c95cde6e]

goroutine 17 [running, locked to thread]:
runtime.throw(0x5601c995512e, 0x5)
	/opt/go/src/runtime/panic.go:617 +0x74 fp=0xc00005cc80 sp=0xc00005cc50 pc=0x5601c95f8314
runtime.sigpanic()
	/opt/go/src/runtime/signal_unix.go:397 +0x405 fp=0xc00005ccb0 sp=0xc00005cc80 pc=0x5601c960cac5
indexbytebody(0x65726f616869656d, 0xa93, 0x0, 0x0, 0xa93, 0x0, 0x65726f616869656d, 0x65726f616869656d, 0xa93, 0xc00005cd58, ...)
	/opt/go/src/internal/bytealg/indexbyte_amd64.s:124 +0xce fp=0xc00005ccb8 sp=0xc00005ccb0 pc=0x5601c95cde6e
runtime.findnull(0x65726f616869656d, 0x0)
	/opt/go/src/runtime/string.go:448 +0x87 fp=0xc00005cd10 sp=0xc00005ccb8 pc=0x5601c9612547
runtime.gostring(0x65726f616869656d, 0x0, 0x0)
	/opt/go/src/runtime/string.go:314 +0x31 fp=0xc00005cd68 sp=0xc00005cd10 pc=0x5601c96121f1
main._Cfunc_GoString(...)
	_cgo_gotypes.go:104
main.Client_NewUser(0x7fff19baa010, 0x0)
	/home/fhz8/gitee/powerchat/client/libclient/exports.go:110 +0x4c fp=0xc00005ce90 sp=0xc00005cd68 pc=0x5601c994beac
main._cgoexpwrap_2f6c8129f4f7_Client_NewUser(0x7fff19baa010, 0x7f4fd25ce85b)
	_cgo_gotypes.go:184 +0x2d fp=0xc00005ceb0 sp=0xc00005ce90 pc=0x5601c994ab4d
runtime.call32(0x0, 0x7fff19ba9f00, 0x7fff19ba9f90, 0x10)
	/opt/go/src/runtime/asm_amd64.s:519 +0x3d fp=0xc00005cee0 sp=0xc00005ceb0 pc=0x5601c962278d
runtime.cgocallbackg1(0x0)
	/opt/go/src/runtime/cgocall.go:314 +0x18e fp=0xc00005cf58 sp=0xc00005cee0 pc=0x5601c95cf6ee
runtime.cgocallbackg(0x0)
	/opt/go/src/runtime/cgocall.go:191 +0xcb fp=0xc00005cfc0 sp=0xc00005cf58 pc=0x5601c95cf4bb
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/opt/go/src/runtime/asm_amd64.s:773 +0x9a fp=0xc00005cfe0 sp=0xc00005cfc0 pc=0x5601c9623d9a
runtime.goexit()
	/opt/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x5601c96244f1

goroutine 19 [chan receive]:
main.startFileServ(0x5601c9d58260, 0xc00004ee00)
	/home/fhz8/gitee/powerchat/client/libclient/files.go:83 +0x101
main.client(0xc000128000)
	/home/fhz8/gitee/powerchat/client/libclient/client.go:59 +0x2c5
created by main.main_init
	/home/fhz8/gitee/powerchat/client/libclient/client.go:431 +0x38a

goroutine 5 [chan receive]:
main.httpProxy2(0x5601c9d5aa00, 0xc00004ee00)
	/home/fhz8/gitee/powerchat/client/libclient/http.go:19 +0x63
created by main.client
	/home/fhz8/gitee/powerchat/client/libclient/client.go:49 +0x15c

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7f4fc856ae38, 0x72, 0x0)
	/opt/go/src/runtime/netpoll.go:182 +0x58
internal/poll.(*pollDesc).wait(0xc00012c198, 0x72, 0x0, 0x0, 0x5601c9956a9b)
	/opt/go/src/internal/poll/fd_poll_runtime.go:87 +0x9d
internal/poll.(*pollDesc).waitRead(...)
	/opt/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00012c180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/internal/poll/fd_unix.go:384 +0x1bc
net.(*netFD).accept(0xc00012c180, 0x0, 0x0, 0xc00005eec0)
	/opt/go/src/net/fd_unix.go:238 +0x44
net.(*TCPListener).accept(0xc000010050, 0xc00005eed8, 0xc00005eee0, 0x0)
	/opt/go/src/net/tcpsock_posix.go:139 +0x34
net.(*TCPListener).Accept(0xc000010050, 0x5601c9d4dcf8, 0xc0000147b0, 0xf, 0xc0000147c0)
	/opt/go/src/net/tcpsock.go:260 +0x4a
main.localServe(0x5601c9d62e40, 0xc00004ee00, 0xc000070070)
	/home/fhz8/gitee/powerchat/client/libclient/client.go:322 +0x3d1
created by main.client
	/home/fhz8/gitee/powerchat/client/libclient/client.go:52 +0x1b2

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7f4fc856af08, 0x72, 0xffffffffffffffff)
	/opt/go/src/runtime/netpoll.go:182 +0x58
internal/poll.(*pollDesc).wait(0xc00012c098, 0x72, 0x700, 0x75d, 0xffffffffffffffff)
	/opt/go/src/internal/poll/fd_poll_runtime.go:87 +0x9d
internal/poll.(*pollDesc).waitRead(...)
	/opt/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00012c080, 0xc000138000, 0x75d, 0x75d, 0x0, 0x0, 0x0)
	/opt/go/src/internal/poll/fd_unix.go:169 +0x19d
net.(*netFD).Read(0xc00012c080, 0xc000138000, 0x75d, 0x75d, 0x203000, 0x0, 0x71d)
	/opt/go/src/net/fd_unix.go:202 +0x51
net.(*conn).Read(0xc000010010, 0xc000138000, 0x75d, 0x75d, 0x0, 0x0, 0x0)
	/opt/go/src/net/net.go:177 +0x6b
crypto/tls.(*atLeastReader).Read(0xc00000e860, 0xc000138000, 0x75d, 0x75d, 0x0, 0xba, 0xc00005dbd8)
	/opt/go/src/crypto/tls/conn.go:761 +0x62
bytes.(*Buffer).ReadFrom(0xc00004f058, 0x5601c9d58280, 0xc00000e860, 0x5601c95d5bf7, 0x5601c9ce9b40, 0x5601c9d37f80)
	/opt/go/src/bytes/buffer.go:207 +0xbf
crypto/tls.(*Conn).readFromUntil(0xc00004ee00, 0x5601c9d58620, 0xc000010010, 0x5, 0xc000010010, 0x33)
	/opt/go/src/crypto/tls/conn.go:783 +0xfa
crypto/tls.(*Conn).readRecordOrCCS(0xc00004ee00, 0x5601c9d4e500, 0xc00004ef38, 0x5601c95d7b55)
	/opt/go/src/crypto/tls/conn.go:590 +0x127
crypto/tls.(*Conn).readRecord(...)
	/opt/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00004ee00, 0xc00001458e, 0x2, 0x2, 0x0, 0x0, 0x0)
	/opt/go/src/crypto/tls/conn.go:1236 +0x139
io.ReadAtLeast(0x7f4fc8094078, 0xc00004ee00, 0xc00001458e, 0x2, 0x2, 0x2, 0x5601c95d5bf7, 0x5601c9ce9b40, 0x5601c9d46760)
	/opt/go/src/io/io.go:310 +0x8a
io.ReadFull(...)
	/opt/go/src/io/io.go:329
main.ReadMsg(0x7f4fc8094078, 0xc00004ee00, 0xc00004ee00, 0x7f4fc8094078, 0xc00004ee00, 0x0, 0x0)
	/home/fhz8/gitee/powerchat/client/libclient/cmds.go:97 +0x88
main.readConn(0x5601c9d62e40, 0xc00004ee00)
	/home/fhz8/gitee/powerchat/client/libclient/client.go:343 +0x73
created by main.client
	/home/fhz8/gitee/powerchat/client/libclient/client.go:54 +0x1e0

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x7f4fc856ad68, 0x72, 0x0)
	/opt/go/src/runtime/netpoll.go:182 +0x58
internal/poll.(*pollDesc).wait(0xc00012c218, 0x72, 0x0, 0x0, 0x5601c9956a9b)
	/opt/go/src/internal/poll/fd_poll_runtime.go:87 +0x9d
internal/poll.(*pollDesc).waitRead(...)
	/opt/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00012c200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/internal/poll/fd_unix.go:384 +0x1bc
net.(*netFD).accept(0xc00012c200, 0x5601c9d1ef20, 0x50, 0xc00012e780)
	/opt/go/src/net/fd_unix.go:238 +0x44
net.(*TCPListener).accept(0xc000010070, 0xc00004e700, 0x7f4fcb7b9008, 0x0)
	/opt/go/src/net/tcpsock_posix.go:139 +0x34
net.(*TCPListener).AcceptTCP(0xc000010070, 0x5601c95d83ea, 0x30, 0x5601c9d1ef20)
	/opt/go/src/net/tcpsock.go:247 +0x4a
net/http.tcpKeepAliveListener.Accept(0xc000010070, 0x5601c9d1ef20, 0xc00012aab0, 0x5601c9cdcde0, 0x5601c9fdda90)
	/opt/go/src/net/http/server.go:3264 +0x31
net/http.(*Server).Serve(0xc000164410, 0x5601c9d5fa00, 0xc000010070, 0x0, 0x0)
	/opt/go/src/net/http/server.go:2859 +0x22f
net/http.(*Server).ListenAndServe(0xc000164410, 0xc000164410, 0x1ff)
	/opt/go/src/net/http/server.go:2797 +0xe6
net/http.ListenAndServe(...)
	/opt/go/src/net/http/server.go:3037
main.startMyHttpServe(0xc0000147b0, 0xf, 0xc0000147c0, 0xe)
	/home/fhz8/gitee/powerchat/client/libclient/embedserver.go:30 +0x13e
created by main.localServe
	/home/fhz8/gitee/powerchat/client/libclient/client.go:318 +0x2fa

goroutine 11 [chan receive]:
main.httpRespRouter()
	/home/fhz8/gitee/powerchat/client/libclient/http.go:148 +0x63
created by main.localServe
	/home/fhz8/gitee/powerchat/client/libclient/client.go:320 +0x32f
[1]    17679 abort      sudo ./PowerChat-linux.glibc2.14-x86_64.AppImage
`
                   -`                    sunhl@ArchLinux 
                  .o+`                   --------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: W650KL 
               `+oooooo:                 Kernel: 4.20.13-arch1-1-ARCH 
               -+oooooo+:                Uptime: 2 days, 11 hours, 41 mins 
             `/:-:++oooo+:               Packages: 1084 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.7.1 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           WM: i3 
         ./ooosssso++osssssso+`          Theme: Flat-Remix-GTK [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: Arc [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: terminator 
      :osssssss/        osssso+++.       CPU: Intel i7-7700 (8) @ 4.200GHz 
     /ossssssss/        +ssssooo/-       GPU: Intel HD Graphics 630 
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce MX150 
  `+sso+:-`                 `.-/+oso:    Memory: 4299MiB / 15923MiB 
 `++:.                           `-/+/
 .`                                 `/

**Comment by rocket049** [comment]
非常感谢您的反馈，现已修复了改BUG。
经研究，此BUG和您的操作系统无关。
因为本程序从v1.2升级到v1.3，窗口和后端程序之间的调用从rpc模式改为C函数调用模式，期间由于本人的疏忽，定义了错误的C语言结构体，引发了该错误，与运行平台无关。
