### ISSUE TITLE
Please do not put AppImage into a gz or other archive

### ISSUE THREAD

**Issue by probonopd** [rocket049/powerchat#3]
Please do **not** put PowerChat-linux.glibc2.14-x86_64.AppImage into a `.gz`

While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional appimaged daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

Reference:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by rocket049** [comment]
thank you.

I put the appimage on another site: https://gitee.com/rocket049/powerchat/releases , it will be damaged after download.
So, I put it into a gz to avoid damage.

**Comment by probonopd** [comment]
What?! Please explain. Putting the AppImage on another site should not damage it.

**Comment by probonopd** [comment]
Can you upload a pure AppImage so that I can test please? Thanks.

**Comment by rocket049** [comment]
you can try it now:  https://gitee.com/rocket049/powerchat/releases/v1.3.18

**Comment by rocket049** [comment]
@probonopd It seems they fix the probrom, the new appimage is not damaged.

**Comment by probonopd** [comment]
It needs a login to download, hence cannot run this automated test...

Can you upload to https://github.com/rocket049/powerchat/releases?

**Comment by rocket049** [comment]
@probonopd I will upload appimage ,as you wish.

**Comment by probonopd** [comment]
Getting

```
powerchat: symbol lookup error: powerchat: undefined symbol: gtk_menu_popup_at_pointer
```

On which distribution was this built? Can you build on Ubuntu trusty or xenial? This Gtk+ function was only introduced in GTK+ 3.22 which not every distribution has... it's too new for some.

**Comment by rocket049** [comment]
@probonopd try powerchat-debian，it can run on debian stable.

**Comment by rocket049** [comment]
@probonopd The new appimage  has replace gtk_menu_popup_at_pointer with gtk_menu_popup.
You can try it again.

**Comment by probonopd** [comment]
Thank you 👍 

Can you test what happens when the machine is not connected to the internet? It should at least show a graphical dialog box saying you need to go online. Thanks.

**Comment by rocket049** [comment]
You can use command line to read error message.

**Comment by probonopd** [comment]
Not if you double-click the icon, then you can't see the message.
